Feat/whitelist dependency
DLC-link/dlc-btc-website pull request #131
Opened 2024-07-11 14:15 UTC by scolear

2024-07-11 15:02 UTC, rozanagy approved these changes
lgtm

2024-07-11 15:09 UTC, Polybius93 requested changes
Nice job @rozanagy @scolear ! I left a question, if that is answered (or fixed) we can merge it!

2024-07-11 15:09 UTC, Polybius93 commented on src/app/components/header/components/tabs.tsx
> +    void checkWhitelisting(address);
```ts
 address && void checkWhitelisting(address);
 ```
 
 Then we could remove the optionality of this value and the check inside the function.

2024-07-11 15:09 UTC, Polybius93 commented on src/app/components/header/components/tabs.tsx
> +        if (!isWhitelistingEnabled) return true;
This part I don't get. Isn't ``isWhitelistingEnabled`` a function that returns a ``Promise<boolean>``. So that function should be called and awaited.

2024-07-12 09:00 UTC, rozanagy commented on src/app/components/header/components/tabs.tsx
> +    void checkWhitelisting(address);
sadly not a good option, bc then when the user is logged out the tabs are still visible.

2024-07-12 09:35 UTC, Polybius93 approved these changes

2024-07-12 09:36 UTC, merged