feat: add wagmi package
DLC-link/dlc-btc-website pull request #149
Opened 2024-08-02 12:47 UTC by Polybius93

This pull request introduces the ``wagmi`` library to enhance the handling of *Ethereum wallets* in our application. Additionally, it removes the now redundant ``account`` slice from the Redux store.

2024-08-02 13:21 UTC, scolear commented on src/app/components/mint-unmint/components/walkthrough/walkthrough.tsx
> +              <Button variant={'vault'} onClick={async () => await addToken()}>
ohh beautiful

2024-08-02 13:23 UTC, scolear commented on src/app/components/mint-unmint/mint-unmint.tsx
> +export function MintUnmint(): React.JSX.Element {
im not sure i understand what's happening in this file, could you elaborate?

2024-08-02 13:54 UTC, scolear commented on src/app/components/modals/select-wallet-modal/select-wallet-modal.tsx
> +    await delay(2500);
this is so that you can remove it and claim that you increased performance in two months?

2024-08-02 13:57 UTC, scolear commented on src/app/hooks/use-points.ts
> +        const events = await fetchTransfersForUser(chain!, address!);
not a fan of `!`, isnt there a better way here?

2024-08-02 13:59 UTC, scolear approved these changes
Love it generally. Left some comments

2024-08-02 13:59 UTC, scolear commented on src/app/components/mint-unmint/components/unmint/components/unmint-vault-selector.tsx
> +                networkID: chainId?.toString() as EthereumNetworkID,
In another PR ofc

2024-08-02 15:25 UTC, Polybius93 commented on src/app/components/mint-unmint/components/unmint/components/unmint-vault-selector.tsx
> +                networkID: chainId?.toString() as EthereumNetworkID,
Totally agree! Thank you for suggesting!

2024-08-02 15:25 UTC, Polybius93 commented on src/app/components/mint-unmint/components/walkthrough/walkthrough.tsx
> +              <Button variant={'vault'} onClick={async () => await addToken()}>
Thank you!

2024-08-02 15:26 UTC, Polybius93 commented on src/app/components/mint-unmint/mint-unmint.tsx
> +export function MintUnmint(): React.JSX.Element {
So ``account`` slice doesn't exist anymore, so I removed it up one level, and then I noticed that this doesn't even require ``address`` checks since this tab is only visible when the user is logged in.

2024-08-02 15:28 UTC, Polybius93 commented on src/app/components/modals/select-wallet-modal/select-wallet-modal.tsx
> +    await delay(2500);
Nice idea, but no, I didn't want the modal to disappear immediately, so the user can acknowledge that the connection was successful.

2024-08-02 15:29 UTC, Polybius93 commented on src/app/hooks/use-points.ts
> +        const events = await fetchTransfersForUser(chain!, address!);
Yes, I can handle the undefined and remove the exclamation mark.

2024-08-02 15:29 UTC, Polybius93 commented
> Love it generally. Left some comments

Thank you!

2024-08-05 10:54 UTC, scolear commented on src/app/hooks/use-vaults.ts
> +    isConnected && chain && isEnabledEthereumNetwork(chain) && void fetchVaultsIfReady(address!);
`if (isConnected && chain && isEnabledEthereumNetwork(chain)) void fetchVaultsIfReady(address!);`
makes more sense semantically imo

2024-08-05 10:56 UTC, scolear requested changes
Just that one comment, otherwise great!

2024-08-05 11:18 UTC, scolear approved these changes

2024-08-05 12:27 UTC, merged