fix: adjust height of points box and fix decimal format
DLC-link/dlc-btc-website pull request #206
Opened 2024-11-04 14:00 UTC by rozanagy

This pull request includes several changes to the points table components and utilities in the `src/app/components/points` directory. The most important changes involve adding a new utility function for formatting numbers, updating the points table item display, and adjusting layout properties for better alignment and spacing.

<img width="645" alt="Screenshot 2024-11-04 at 14 56 28" src="https://github.com/user-attachments/assets/6352bf6d-8bba-4d23-b326-b56038fed437">
<img width="1415" alt="Screenshot 2024-11-04 at 14 24 18" src="https://github.com/user-attachments/assets/62eab9ea-c7f0-4e7e-ab3f-fb4cf4c19071">

2024-11-04 14:31 UTC, scolear requested changes

2024-11-04 15:55 UTC, sosaucily commented on src/app/components/points/components/points-table/components/points-table-item.tsx
> +              {formatToThreeDecimals(unshiftValue(currentTokens))}
Robert you want to see 8 decimal places?

2024-11-05 09:15 UTC, scolear commented on src/app/components/points/components/points-table/components/points-table-item.tsx
> +              {formatToThreeDecimals(unshiftValue(currentTokens))}
Yeah I am happy with the 4 decimals. Anyway my test data was wrong, and was testing with 1 sats instead of 1 BTC (: 

So I am fine with the latest update!

2024-11-05 09:19 UTC, scolear approved these changes

2024-11-05 10:01 UTC, merged