Feat/about page
DLC-link/dlc-btc-website pull request #38
Opened 2023-12-18 06:03 UTC by rozanagy

draft pr is ready for the first check

2023-12-18 10:05 UTC, Polybius93 requested changes
Really great job! I've made some code uniformity related comments, but overall, this is really clean and understandable. The lint-commit github action is failing and I see that you used _wip_ in your commit messages, which might be the cause of the failing action. To fix this you'll need to do an interactive rebase to rename these messages, also, please take a look at conventional commits, to see how you can pass this action. Thank you!

2023-12-19 06:33 UTC, sosaucily commented on src/app/components/how-it-works/bottom/components/how-to-mint.tsx
> +                <Text as={'span'} color={'rgba(154, 201, 255, 1)'}>
Can this be the first use of 'white?' 😄

2023-12-19 07:35 UTC, rozanagy commented on src/app/components/how-it-works/bottom/components/how-to-mint.tsx
> +                <Text as={'span'} color={'rgba(154, 201, 255, 1)'}>
i guess you know Jesse that this is not about that 'white', right? :D in that case, good joke.

2023-12-19 08:31 UTC, rozanagy commented on src/app/components/how-it-works/bottom/components/audit-reports.tsx
> +    <CustomCard width={'488px'} height={'152px'} padding={'25px'}>
here, the width, height and padding are the name of the parameters, would you like me change it here too?
for other places it makes sense, but it is nice if a props parameter is descriptive.

2023-12-19 08:50 UTC, rozanagy commented on src/app/components/how-it-works/middle/middle-section.tsx
> +      minW={'100vw'}
i only used vw here, because the width of this element is bigger than the parent's element. maybe the structuring is not correct, but this was the only way where I was able to achieve the full width gradient.

2023-12-19 08:52 UTC, rozanagy commented on src/app/components/how-it-works/middle/middle-section.tsx
> +      backgroundRepeat={'no-repeat'}
correct. i just copy pasted the ui props from the design.

2023-12-19 08:52 UTC, rozanagy commented on src/app/components/how-it-works/middle/middle-section.tsx
> +      backgroundPosition={'0% 0%'}
same as above. correct.

2023-12-19 09:25 UTC, Polybius93 commented on src/app/components/how-it-works/bottom/components/audit-reports.tsx
> +    <CustomCard width={'488px'} height={'152px'} padding={'25px'}>
Oh, sorry, you are right, I didn't see that this is a custom component of yours! All good!

2023-12-22 13:42 UTC, Polybius93 approved these changes
Great job, @rozanagy! The components are thoughtfully structured, making it easy to comprehend every part of the updates.

2023-12-22 14:05 UTC, merged